### ISSUE TITLE
unspecified dates ("1990-uu-uu") don't parse.

### ISSUE THREAD

**Issue by workergnome** [inukshuk/edtf.js#14]
As noted in http://www.loc.gov/standards/datetime/pre-submission.html#unspecified, "1990-uu-uu" is a valid EDTF date.  However, when run through edtf.js, it throws a parse error.

**Comment by inukshuk** [comment]
The edtf.js parser is written for the upcoming ISO 8601 standard which will supercede the original EDTF (see the note all the way at the top of the page you linked to). In IS0 8601 the unspecified marker is 'X' not 'u'.
