### ISSUE TITLE
Update to support latest spec

### ISSUE THREAD

**Issue by inukshuk** [inukshuk/edtf.js#16]
- [ ] Use `..` instead of `*` in open L2 intervals

**Comment by bdarcus** [comment]
Since EDTF has been since adopted as part of ISO 8601-2, would be nice to fix this now.

**Comment by inukshuk** [comment]
Yes, it's about time, thanks!

This is fixed in 3.0.1

**Comment by bdarcus** [comment]
Thanks!

For the record, I'm just going to link back to citation-style-language/schema#284.
