### ISSUE TITLE
Usage in closed-source commercial product

### ISSUE THREAD

**Issue by thegreatanon** [inukshuk/edtf.js#33]
We're developing an application that is only accessible to our customers. We are in need of a EDTF implementation in javascript, and found this repository which matches our needs exactly. We've also looked at edtfy but that misses some functioanlity we need.

Our code is closed-source, which due to the AGPL3 license of this repository means that we are unable to use it. 

Would it be possible to discuss some specific alternate license that allows commercial use without having to open everything under AGPL3?

**Comment by inukshuk** [comment]
Thanks for asking! I'll check with my team and costumers, but yes, I'm sure we can provide you with a more permissive license for use in your application, but we would expect you make a reasonable donation to support the project in return. If you're interested in doing so, I'm going to setup a GitHub Sponsors page for that purpose.

**Comment by inukshuk** [comment]
On second thought, we'll just change to BSD style license anyway (you're still welcome to sponsor if we set up the page at some point!).

**Comment by thegreatanon** [comment]
Thanks for the response inukshuk! We're very happy with this. I'll take it up with the higher-ups regarding potential donation.
