### ISSUE TITLE
AssertionError when calling edtf("{1978,1988}") in prod

### ISSUE THREAD

**Issue by berger-n** [inukshuk/edtf.js#36]
it's ok when calling `parse("{1978,1988}")`, I get:
```
{
    "values": [
        {
            "type": "Date",
            "level": 0,
            "values": [
                1978
            ]
        },
        {
            "type": "Date",
            "level": 0,
            "values": [
                1988
            ]
        }
    ],
    "level": 2,
    "type": "List"
}
```

but [next line](https://github.com/buda-base/blmp-client/blob/6b7ed39a02ff60f2d747756c3ff3214e63ca26c0/src/routes/entity/containers/ValueList.tsx#L1130), calling `edtf("{1978,1988}")`, I get this error:
```
{
    "name": "AssertionError",
    "actual": "n",
    "expected": "List",
    "operator": "==",
    "message": "'n' == 'List'",
    "generatedMessage": true,
    "stack": "AssertionError: 'n' == 'List'\n    at new n (https://editor.bdrc.io/static/js/2.0f6ebddd.chunk.js:2:630854)\n    at V (https://editor.bdrc.io/static/js/2.0f6ebddd.chunk.js:2:633514)\n    at https://editor.bdrc.io/static/js/main.f531b37e.chunk.js:1:13265\n    at set (https://editor.bdrc.io/static/js/2.0f6ebddd.chunk.js:2:79522)\n    at set (https://editor.bdrc.io/static/js/2.0f6ebddd.chunk.js:2:70876)\n    at ht (https://editor.bdrc.io/static/js/2.0f6ebddd.chunk.js:2:25475)\n    at At (https://editor.bdrc.io/static/js/2.0f6ebddd.chunk.js:2:26952)\n    at https://editor.bdrc.io/static/js/2.0f6ebddd.chunk.js:2:27806\n    at Object.replaceState (https://editor.bdrc.io/static/js/2.0f6ebddd.chunk.js:2:43869)\n    at Nt (https://editor.bdrc.io/static/js/2.0f6ebddd.chunk.js:2:27703)"

}
```

this error only occurs after build, in a react app deployed in prod
not on a dev server running locally
which makes it hard to track in minified built code...

not sure how but this could be related to some trouble I had importing the edtf library
I ended up using [this line](https://github.com/buda-base/blmp-client/blob/6b7ed39a02ff60f2d747756c3ff3214e63ca26c0/src/routes/entity/containers/ValueList.tsx#L53-L55) to make it work:

```
import edtf, { parse } from "edtf/dist/../index.js" /
```

because I got this error:
```
Attempted import error: 'parse' is not exported from 'edtf'.
```

when using the regular one:
```
import edtf, { parse } from "edtf"
```

**Comment by inukshuk** [comment]
I can't reproduce this, so I'd follow-up on the idea that this is related to a bundling issue. Ideally, you should be able to just import from 'edtf' but if your bundler does not support [package entry points](https://nodejs.org/dist/latest-v17.x/docs/api/packages.html#package-entry-points) it would fallback to the Common JS version -- I suspect this is what happened for your (in this case you can still access the same functionality via `edtf.parse`) but I'd make sure to configure your bundler so that you that 'edtf' resolves to the [correct entry point for ES modules](https://github.com/inukshuk/edtf.js/blob/main/package.json#L9).

Otherwise, if you want to debug this in the bundled code, I'd suggest to either disable minification so that you can use the debugger, or else insert some log statements [particularly around here](https://github.com/inukshuk/edtf.js/blob/main/src/edtf.js#L23) in order to figure out what's going on. You see that the constructors are mapped to type names, so this is something where an issue code-obfuscation might come into play.

**Comment by berger-n** [comment]
thanks for the answer

I was hoping using `edtf.parse` could work but it doesn't because `edtf` is considered a string with value `/static/media/index.cdefe064.cjs`, not an object, when I use `import edtf from "edtf"` (what you mean by fallback to Common JS version I guess)

> make sure to configure your bundler so that you that 'edtf' resolves to the [correct entry point for ES modules](https://github.com/inukshuk/edtf.js/blob/main/package.json#L9)

I'm sorry but I'm not sure to understand what is implied here, could you explain a bit more please?

**Comment by berger-n** [comment]
thanks a lot for your help!

found this in `main.chunk.js` 
```
var edtf__WEBPACK_IMPORTED_MODULE_2__ = __webpack_require__(/*! edtf */ "./node_modules/edtf/dist/index.cjs");
```
so the first answer must be `./node_modules/edtf/dist/index.cjs`

what puzzles me most is why `import edtf from "edtf"` returns the  string `/static/media/index.cdefe064.cjs`?
I didn't know this was even possible I must say

**Comment by berger-n** [comment]
I think I'm more interested in

> find out how to tell Webpack to load the appropriate [ESM] module

but I can't figure out yet how this can be configured in webpack, is this related https://webpack.js.org/guides/ecma-script-modules/#flagging-modules-as-esm ? yet *Named exports are not available* so it did not solve my problem (but it did not change that it loads `./node_modules/edtf/dist/index.cjs` instead of `./node_modules/edtf/index.js`... so that may not be what you were talking about above)

thanks again for your help

**Comment by inukshuk** [comment]
Yes, I agree that it should be preferred to have Webpack pull in the ESM module. edtf.js [identifies as an ESM module by setting the package type](https://github.com/inukshuk/edtf.js/blob/main/package.json#L5). However, it's a dual-module with multiple entry points, defined by 'export' as I've linked to earlier. I think what happens is that Webpack uses [the 'main' property](https://github.com/inukshuk/edtf.js/blob/main/package.json#L6) which points to a `.cjs` file -- the file extension overrides the fact that the entire module is defined as ESM. However, 'main' is only there as a fallback: [if a module loader supports 'export' it's supposed to ignore 'main'](https://nodejs.org/dist/latest-v17.x/docs/api/packages.html#package-entry-points). To me it looks like Webpack does not support this feature, and therefore loads the fallback CJS module. If that's the case you can probably work around it in the webpack config with some kind of override that instructs it to load 'edtf/index.js' instead.

**Comment by inukshuk** [comment]
Or perhaps there is a Webpack plugin or config setting which enables support for Node's package entry points.

**Comment by berger-n** [comment]
looks like `"main"` entry point is preferred to `"exports"` 
indeed I can load `edtf` as an ESM module when I remove [this line](https://github.com/inukshuk/edtf.js/blob/988e2ebf9b3f81a3014f918a8d147af344f0b4b3/package.json#L6) from `package.json`
for `typescript` to run I also had to add an `index.d.ts` with content `declare module 'edtf';` at the root of `edtf` module directory
all of which solved the first problem! thanks a lot

```
var edtf__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(/*! edtf */ "./node_modules/edtf/index.js");
```

unfortunately the initial issue still occurs when module properly loaded as ESM
but thanks to your suggestion I was able to track down where exactly it fails:

https://github.com/inukshuk/edtf.js/blob/988e2ebf9b3f81a3014f918a8d147af344f0b4b3/src/list.js#L31

see screenshots below, output shown is that of current `args` and `typeof` of its content, then values of both arguments of `assert`:
- when running app in dev mode: 

![image](https://user-images.githubusercontent.com/33383857/159456015-b7715708-2e89-4868-8591-ac8ca698ceb5.png)

- when running built app:

![image](https://user-images.githubusercontent.com/33383857/159456492-0a1269f8-1152-4158-ba97-84982555657b.png)

hope this helps!

**Comment by inukshuk** [comment]
OK so if I understand your screenshots correctly, `this.type` in the List constructor (right before the assert) returns 'n'?

If hat's the case then it's possible that you're renaming the class name when building the app. `this.type` should evaluate to `this.constructor.name` -- in the context of the List constructor this should return 'List' unless the `List` class has been renamed

**Comment by berger-n** [comment]
issue was due to webpack minimizer renaming classnames
I [forked](https://github.com/buda-base/edtf.js) your repo and made minor changes
now everything's fine in our app
thanks again for your help!

**Comment by bdarcus** [comment]
Is there any reason why note to add the typescript declaration file here, @berger-n? E.g. a PR?

**Comment by berger-n** [comment]
@bdarcus indeed, for the record we mostly had a bunch of fixes that were very specific to our toolchain:
https://github.com/inukshuk/edtf.js/compare/main...buda-base:edtf.js:main
