### ISSUE TITLE
Day not considered unspecified in month-precision Level 0 date

### ISSUE THREAD

**Issue by v-ji** [inukshuk/edtf.js#37]
Hi, I’m unsure whether this is expected behaviour, but I noticed that constructing a month-precision date by omitting the day part yields a different result compared to a day-precision date when filling the day part with `XX`:

```js
> const edtf = require('edtf')
> edtf.default('1963-12').unspecified.is('day')
0
> edtf.default('1963-12-XX').unspecified.is('day')
192
```

I would expect the method to tell me that the day is unspecified in the first case, too. 
If this is working correctly, what is the intended way of determining that there is no day part?

**Comment by inukshuk** [comment]
Good question. There is an important distinction between a day-precision date with an unspecified day and month-precision date: in the former the day is more than just 'unspecified' it's simply not there, or not important. `1963-12` is basically the entire month of December; while `1963-12-XX` is a single day in December, but it's not specified which one.

You can get/set a month's precision like this:

`edtf('1963-12').precision` should be 2 (i.e., 2 parts) while `1963-12-XX` would have precision 3.

**Comment by v-ji** [comment]
Thank you for your swift reply, that makes a lot of sense!
