### ISSUE TITLE
JSON-schema validator

### ISSUE THREAD

**Issue by retorquere** [inukshuk/edtf.js#38]
I'd like to prepare a PR for a JSON-schema validator, but it'd be convenient if the season-interval option could be a separate option to `parse` rather than the level `3` option before getting to it.

**Comment by inukshuk** [comment]
Yes, that makes sense. Any preference for the option name?

**Comment by retorquere** [comment]
I think the right nomenclature is season-intervals, so then we'd have `seasonIntervals`, as a boolean option.

**Comment by inukshuk** [comment]
Done. We can now define constraints more freely. As before, you can set the `level` and a list of `types` (e.g., if you want level two, but disable Sets or something like that) and we can define any additional features that take priority over this. So for example, `seasonIntevals` will make the parser accept them even though they're at the imaginary level 3. The level 3 stuff still works, but it's really an implementation detail now.

**Comment by retorquere** [comment]
I'm a little lost in the `.cjs` vs `.js` meanings in this repo.

**Comment by inukshuk** [comment]
This is a `type: module` package so you need to use the `.cjs` ending if you add a CommonJS module. But everything should be ES by now (with the exception of the locale loader script... which I should update on this occasion). `dist/index.cjs` is just the auto-generated CommonJS version served if you load the package with `require` -- we should probably remove it from the repo actually.

**Comment by inukshuk** [comment]
Separate module might also make more sense. It's your call! It's definitely good to have the compliance/validation built-in. If you prefer a separate module, I'll try to make a release later today with the `seasonInterval` option.

**Comment by inukshuk** [comment]
I released 4.2.0 to make sure that the dual module still works fine. Looking good so far, so we can either make a PR and make a new release later or a separate module, which ever is best.

**Comment by retorquere** [comment]
I'm OK with putting in more effort to make it part of this library, but I'm not familiar with rollup yet.
