### ISSUE TITLE
Year > 9999?

### ISSUE THREAD

**Issue by retorquere** [inukshuk/edtf.js#9]
EDTF L1 (not the WD) accepts `y170000002` as a valid date, how must I pass that to `edtf.js`? I've tried removing the leading `y` but that doesn't do it.

**Comment by inukshuk** [comment]
See section 4.6 years exceeding four digits. The syntax is now with a capital `Y`, i.e., `Y170000002` or using exponential form `Y17E7`.

**Comment by SylvainBigonneau** [comment]
Shouldn't `edtf('9999').next()` return a `Year` then ?

Because right now it seems a little confusing that:

```javascript
let date = edtf('9999').next()
let edtfString = date.edtf // '10000'
let dateCopy = edtf(edtfString)
```

triggers an error since "10000" is an incorrect EDTF notation, if I understand correctly?

**Comment by inukshuk** [comment]
Hmm, that's a good question. I think .next() should probably still return a `Date`. But when formatted to a string it should return it as `Y10000`.
